name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:

      - name: compile_and_build
      run : gcc -shared primes.c -O3 -o primes_impl.so
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
